export { HeroSection } from './HeroSection/HeroSection'
export { Services } from './Services/Services'
export { News } from './News/News'
export { Banner } from './Banner/Banner'
export { Corporate } from './Corporate/Corporate'